- name: tar remote jdk-7u79-linux-x64.tar.gz
  unarchive: src={{ jdk_path }}/files/jdk-7u79-linux-x64.tar.gz dest=/opt copy=yes mode=0755
- name: soft link
  file: src=/opt/jdk1.7.0_79 dest=/opt/java state=link
- name: java_profile config
  shell: /bin/echo {{ item }} >> /etc/profile && source /etc/profile && /bin/echo {{ item }} >> /root/.bashrc 
  with_items:
    - export JAVA_HOME=/opt/java
    - export JRE_HOME=/opt/java/jre
    - export CLASSPATH=.:\$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:\$JRE_HOME/lib:\$CLASSPATH
    - export PATH=\$JAVA_HOME/bin:\$PATH
